Global:
  use_gpu: False
  use_wandb: False
  epoch_num: 10
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: ./output/cls/res18/
  save_epoch_step: 3
  # evaluation is run every 5000 iterations after the 4000th iteration
  eval_batch_step: [0, 5000]
  cal_metric_during_train: False
  pretrained_model:
  checkpoints:
  infer_img: doc/imgs_words_en/word_10.png

Architecture:
  name: ResNet
  layers: 18
  num_classes: 10

Loss:
  name: ClsLoss

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
  regularizer:
    name: 'L2'
    factor: 0

PostProcess:
  name: ClsPostProcess

Metric:
  name: ClsMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /root/workspace/dataset/cifar10/cifar-10-batches-py/train
    label_file_list:
      - /root/workspace/dataset/cifar10/cifar-10-batches-py/train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: True
      - NormalizeImage:
      - ClsLabelEncode:
          label_list: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] # Class handling label
      - KeepKeys:
          keep_keys: ['image', 'label'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 32
    drop_last: True
    num_workers: 1

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /root/workspace/dataset/cifar10/cifar-10-batches-py/test
    label_file_list:
      - /root/workspace/dataset/cifar10/cifar-10-batches-py/test.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: True
      - NormalizeImage:
      - ClsLabelEncode: # Class handling label
          label_list: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] # Class handling label
      - KeepKeys:
          keep_keys: ['image', 'label'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 32
    num_workers: 1
